### ISSUE TITLE
Unable to follow Cursive REPL instructions as stated

### ISSUE THREAD

**Issue by kahunamoore** [mfikes/tubular#5]
I'm trying to use Cursive w/ an existing Socket REPL (Arcadia) but am unable to connect using any of the options available in Cursive as it doesn't seem to support socket REPLs. I found this repo and was following the instructions but was unable to complete the Cursive Remote REPL configuration.

In the Tubular README it states:

"First ensure Tubular is set up as a dependency. Then when creating a Cursive REPL, don't pick either of the nREPL options. Instead choose: “Use clojure.main in normal JVM process”.

I cannot find this exact wording for a REPL option anywhere in this version of Cursive. I do remember this option in a REPL configuration when using previous versions of Cursive.

Is there a new/different way of configuring Tubular for Cursive that I'm missing?

I tried various combinations of Cursive Remote REPLs but all of them either attempt to connect to nREPLs or get a connection refused message. I know my server is running because I can connect using telnet.

My setup: Windows 10 (:-( because Unity/VR development), IntelliJ 2018.3.4 CE, Cursive v1.8.1-eap2-2018.3), Tubular master/HEAD.

**Comment by mfikes** [comment]
You need to choose a _Local_ REPL. (Tubular then runs inside that "local" REPL, and acts as a client of the "remote" target Socket REPL server—Arcadia in your case.)

Having said that, in Cursive v1.8.0-2018.3, the first section of the (local) REPL configuration panel is now entitled "Which type of REPL to run", and it allows you to choose between "nREPL" and "clojure.main"; you want the latter.

**Comment by kahunamoore** [comment]
Thank you so much. I knew I was missing something. I did try a local REPL at one point but don’t remember what happened... I’ll give it another try now that I know that is the correct REPL type.

**Comment by kahunamoore** [comment]
Closing this b/c it seems I was doing it wrong...
